# config.py

# ===== RISK MANAGEMENT =====
TAKE_PROFIT_PERCENT = 5.0   # 5%
STOP_LOSS_PERCENT = 2.0     # 2%

# ===== STRATEGY =====
MA_PERIOD = 50
VOLUME_MULTIPLIER = 1.5

TIMEFRAMES = ["1d"]
SCAN_INTERVAL = 60
