# config.py

BINANCE_BASE_URL = "https://api.binance.com"

TIMEFRAMES = ["1d"]

SYMBOLS_LIMIT = 200

MA_PERIOD = 50
VOLUME_MULTIPLIER = 1.5

SCAN_INTERVAL = 60  # seconds

TELEGRAM_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"
TELEGRAM_CHAT_ID = "YOUR_CHAT_ID"
