import os

# TELEGRAM
TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
CHAT_ID = os.getenv("CHAT_ID")

# EXCHANGE
EXCHANGE = "binance"
TOP_COINS = 200

# SCAN INTERVAL
SCAN_INTERVAL = 60

# TIMEFRAMES
SCALP_TF = ["1m", "5m"]
INTRADAY_TF = ["15m", "1h"]
LONG_TF = ["1d", "1w"]

# THRESHOLDS
VOL_SPIKE = 2.2
ATR_EXPANSION = 1.6
VWAP_DEV = 0.5
DELTA_BULL = 0.58
DELTA_BEAR = 0.42
